export const authTypes = {
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_AUTHENTICATING: 'AUTH_AUTHENTICATING',
    AUTH_ERROR: 'AUTH_ERROR'
}

export const registerTypes = {
    REGISTER_ERROR: 'REGISTER_ERROR',
    REGISTER_REGISTERING: 'REGISTER_REGISTERING',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS'
}