export const authTypes = {
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_ERROR: 'AUTH_ERROR'
}

export const registerTypes = {
    REGISTER_ERROR: 'REGISTER_ERROR',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_EMAIL_ERROR: 'REGISTER_EMAIL_ERROR',
    REGISTER_PASSWORD_ERROR: 'REGISTER_PASSWORD_ERROR',
    REGISTER_PASSWORD_MATCH_ERROR: 'REGISTER_PASSWORD_MATCH_ERROR'
}