# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  backend-test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: run tests
      run: |
        cd ethammy-backend/
        npm install
        npm test
        
  frontend-test:
    runs-on: ubutu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: run tests
        run: |
          cd ethammy-frontend/
          npm install
          npm test
          npm run build
